### ISSUE TITLE
Is the Waveshare hat good to use again with your edits?

### ISSUE THREAD

**Issue by sudoMakeThisSecure** [pivoine31/esp32-weather-epd-pvmod#1]
Hay mate,
Just about to buy the hat for the display.

With your code fix, does that mean the Waveshare hat is good to use again. As the display I brought comes with one.
Otherwise, I will have to buy the DESPI-C02 for near $35 US shipped to me.

Also, if I can use this Waveshare hat, do I just connect the extra PWR pin on the hat to VCC, 3.3V or pin 14 on the firebeetle?

In the waveshare docs, it states "3.3V / 5V (The IO level voltage must be consistent with the supply voltage)"

And I also read somewhere that the new PWR wire is to turn the display on and off. So connecting it to VCC might mean its always on, drawing power?

I might also post this in the original git too

**Comment by pivoine31** [comment]
Hi,

I'm not the designer of this weather station, just a guy that has made some modifications to the software. Hence as you have said, it would be a good idea to post the issue on the original L Marzen Git

That being said, I can give you my feeling:
- The fix I integrated in my mod was submitted by dwuhls in issue #62 ; dwuhls was using a rev 2.3 Waveshare hat, hence the fix should work in this case
- Anyway, using a DESPI-C02 does not prevent the problem from occurring ; I have this model and the display starts to loose contrast when the graph fill ratio is around 70% ; so I have the feeling that both are equivalent since both have the problem ; but I have no mean to test the waveshare hat
- The added value of my fix relative to the original dwuhls one is the ability to setup a fill ratio threshold : above the threshold, the low density pattern is used, below the high density pattern is used)
- for information, the despi-c02 may be found on Ali at a better price (the model I bougth: https://fr.aliexpress.com/item/1005004633084221.html?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.2.605aCc4kCc4kq4&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=d8f6c161-87d9-415d-817f-7a91737e7451&_t=gps-id:pcDetailTopMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:d8f6c161-87d9-415d-817f-7a91737e7451,tpp_buckets:668%232846%238112%231997&isseo=y&pdp_npi=4%40dis%21EUR%218.07%218.07%21%21%218.54%218.54%21%402103890917219388201386234ec522%2112000029911597842%21rec%21FR%213410366739%21X&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A)

Best regards

**Comment by sudoMakeThisSecure** [comment]
Sounds good. I will try to use the Waveshare 2.3, that comes with the display and when it gets delivered, I will test it. If possible, keep this issue open for now for a channel for results.

**Comment by pivoine31** [comment]
Did you succeed in your attempt ? if so, we may close the issue.

**Comment by sudoMakeThisSecure** [comment]
Sorry for the late reply. Yes, with this, it loos good so far on the waveshare hat. Although, we have not received lots of rain lately so hard to test.
